export const BEST_SELLER_LOADING = 'BEST_SELLER_LOADING';
export const BEST_SELLER_LOAD_SUCCESS = 'BEST_SELLER_LOAD_SUCCESS';
export const BEST_SELLER_LOAD_FAILURE = 'BEST_SELLER_LOAD_FAILURE';

export const FEATURE_BRAND_LOADING = 'FEATURE_BRAND_LOADING';
export const FEATURE_BRAND_LOAD_SUCCESS = 'FEATURE_BRAND_LOAD_SUCCESS';
export const FEATURE_BRAND_LOAD_FAILURE = 'FEATURE_BRAND_LOAD_FAILURE';

export const CODE_LOADING = 'CODE_LOADING';
export const CODE_LOAD_SUCCESS = 'CODE_LOAD_SUCCESS';
export const CODE_LOAD_FAILURE = 'CODE_LOAD_FAILURE';